version: "3.8"

services:
  db:
    image: mongodb/mongodb-community-server:7.0.11-ubuntu2204
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - db-network

  backend:
    build:
      context: ./simple-lab-mern-test-back
    container_name: backend
    environment:
      - MONGO_CONNECTION_STRING=mongodb://db:27017/simple-lab-mern-test
      - PORT=8080
    command: npm start
    ports:
      - "8080:8080"
    networks:
      - db-network
    depends_on:
      - db

  frontend:
    build:
      context: ./simple-lab-mern-test-front
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    container_name: frontend
    ports:
      - "3000:3000"

networks:
  db-network:
    driver: bridge
