version: "3"

services:
  db:
    image: mongodb/mongodb-community-server:7.0.11-ubuntu2204
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - db-network

  backend:
    build:
      context: ./simple-lab-mern-test-back
    container_name: backend
    environment:
      - MONGO_CONNECTION_STRING=mongodb://db:27017/
      - PORT=8080
    command: npm run dev
    ports:
      - "8080:8080"
    networks:
      - db-network
    volumes:
      - ./simple-lab-mern-test-back:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  frontend:
    build:
      context: ./simple-lab-mern-test-front
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./simple-lab-mern-test-front:/usr/src/app
      - /usr/src/app/node_modules

networks:
  db-network:
    driver: bridge
