version: "3"

services:
  db:
    image: mongodb/mongodb-community-server:7.0.11-ubuntu2204
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - db-network

  backend:
    build:
      context: ./simple-lab-mern-test-back
    container_name: backend
    entrypoint: dockerize -wait tcp://db:27017 -timeout 20s docker-entrypoint.sh
    environment:
      - MONGO_CONNECTION_STRING=mongodb://db:27017/
      - PORT=3000
    command: npm run dev
    ports:
      - "3000:3000"
    networks:
      - db-network
    volumes:
      - ./simple-lab-mern-test-back:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

networks:
  db-network:
    driver: bridge
