name: Run tests for the back-end

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 21.6
        uses: actions/setup-node@v3
        with:
          node-version: 21.6
          cache: "npm"
          cache-dependency-path: simple-lab-mern-test-back/package-lock.json
      - run: npm install
        working-directory: simple-lab-mern-test-back
      - run: npm test
        working-directory: simple-lab-mern-test-back
