name: Cypress tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          working-directory: simple-lab-mern-test-front