name: Run tests for the server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 21.6
      uses: actions/setup-node@v3
      with:
        node-version: 21.6
        cache: 'npm'
    - run: npm install
    - run: npm test
